#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:30:00
#PBS -N preparePRF
#PBS -V

rm -rf output
singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./run.sh"
