#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:30:00
#PBS -N preparePRF
#PBS -V

rm -rf output
time singularity exec --pwd . -e docker://brainlife/freesurfer:6.0.0 bash -c "echo \$(ls) && echo \$FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./run.sh"
