#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=00:30:00
#PBS -N preparePRF
#PBS -V

module load singularity 2> /dev/null

rm -rf output
singularity exec -e docker://brainlife/freesurfer:6.0.0 bash -c "echo $FREESURFER_LICENSE > /usr/local/freesurfer/license.txt && ./convert.sh"

singularity exec -e docker://brainlife/docker-pythonvtk bash -c "pip install nibabel && ./main.py"

if [ -f "surfaces.json" ]
then
    echo 0 > finished
else
    echo "surfaces.json not found"
    echo 1 > finished
    exit 1
fi